name: openwrt-21.02-x86_64

on:
  schedule:
    - cron: '0 18 4/15 * *' # Runs at 02:00 UTC+8 on the 5 and 20th of every month.
  workflow_dispatch:

env:
  TZ: Asia/Shanghai
  BUILD_TARGET: x64
  DEBIAN_FRONTEND: noninteractive

jobs:
  build-openwrt:
    runs-on: ubuntu-20.04
    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
    steps:
      - uses: actions/checkout@v2

      - name: Workspace init
        run: |
          echo "DISTRO_VERSION=$(date +'v%y.%m.%d')" >> $GITHUB_ENV
          sudo bash $GITHUB_WORKSPACE/scripts/init-workspace.bash

      - name: 1-1 Multi-thread compile
        if: success()
        run: |
          bash $GITHUB_WORKSPACE/scripts/prebuild.bash $BUILD_TARGET
          cd $GITHUB_WORKSPACE/openwrt/
          make -j $(($(nproc)+1)) V=s

      - name: 1-2 Single-thread compile
        if: failure()
        run: |
          cd $GITHUB_WORKSPACE/openwrt/
          make -j 1 V=s

      - name: 3 Pack up targets
        if: success()
        run: |
          bash $GITHUB_WORKSPACE/scripts/packup.bash $BUILD_TARGET
          tree $GITHUB_WORKSPACE/out/

      - name: 5 Upload targets to release
        if: success()
        uses: ncipollo/release-action@v1
        with:
          tag: latest
          name: ${{ env.DISTRO_VERSION }}
          body: |
            Auto released by actions
            Now is ${{ env.DISTRO_VERSION }}
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: ${{ github.workspace }}/out/*
          allowUpdates: true
          replacesArtifacts: true

      - name: 4-2 Upload targets
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: openwrt-x86-64-${{ env.DISTRO_VERSION }}
          path: ${{ github.workspace }}/out/
